common-rest/src/main/java/org/uniprot/api/rest/search/AbstractSolrSortClause.java
common-rest/src/test/java/org/uniprot/api/rest/search/AbstractSolrSortClauseTest.java

.. and add null check (to keep Sonarqube happy, even though this check currently is unnecessary)

Add tests to cover AbstractSolrSortClause

---

common-rest/src/main/java/org/uniprot/api/common/repository/search/SolrCursorMarkIterator.java
common-rest/src/main/java/org/uniprot/api/common/repository/search/SolrQueryRepository.java
common-rest/src/main/java/org/uniprot/api/common/repository/search/SolrRequestConverter.java
common-rest/src/main/java/org/uniprot/api/common/repository/search/SolrResultsIterator.java
common-rest/src/main/java/org/uniprot/api/rest/service/BasicSearchService.java
common-rest/src/test/java/org/uniprot/api/common/repository/search/SolrCursorMarkIteratorTest.java
common-rest/src/test/java/org/uniprot/api/common/repository/search/SolrQueryRepositoryIT.java
common-rest/src/test/java/org/uniprot/api/common/repository/search/SolrRequestConverterTest.java

Tests all passing here: https://wwwint.ebi.ac.uk/uniprot/jenkins/job/repo-builder/3/

Remove use of Spring's Query, and provide a Stream<T> getAll() implementation

---

common-rest/src/main/java/org/uniprot/api/rest/output/converter/UniProtEntryFilters.java
common-rest/src/test/java/org/uniprot/api/rest/controller/AbstractGetByIdControllerIT.java
proteome-rest/src/main/java/org/uniprot/api/proteome/controller/GeneCentricController.java
proteome-rest/src/main/java/org/uniprot/api/proteome/controller/ProteomeController.java
support-data-rest/src/main/java/org/uniprot/api/literature/output/LiteratureEntryFilter.java
support-data-rest/src/main/java/org/uniprot/api/taxonomy/output/TaxonomyEntryFilter.java
support-data-rest/src/test/java/org/uniprot/api/disease/DiseaseControllerSearchTestIT.java
support-data-rest/src/test/java/org/uniprot/api/disease/DiseaseSearchControllerIT.java
uniparc-rest/src/test/java/org/uniprot/api/uniparc/controller/UniParcGetIdControllerIT.java
uniparc-rest/src/test/java/org/uniprot/api/uniparc/controller/UniParcSearchControllerIT.java
uniprotkb-rest/src/main/java/org/uniprot/api/uniprotkb/controller/UniprotKBController.java
uniprotkb-rest/src/main/java/org/uniprot/api/uniprotkb/service/UniProtEntryQueryResultsConverter.java

REPLEACES INSTANCE CALL SYNTAX TO STATIC SYNTAX

---

common-rest/src/main/java/org/uniprot/api/rest/validation/ValidSolrSortFields.java
proteome-rest/src/test/java/org/uniprot/api/proteome/controller/GeneCentricGetIdControllerIT.java
proteome-rest/src/test/java/org/uniprot/api/proteome/controller/GeneCentricSearchControllerIT.java
proteome-rest/src/test/java/org/uniprot/api/proteome/controller/ProteomeGetIdControllerIT.java
proteome-rest/src/test/java/org/uniprot/api/proteome/controller/ProteomeSearchControllerIT.java
support-data-rest/src/test/java/org/uniprot/api/disease/DiseaseControllerTest.java
support-data-rest/src/test/java/org/uniprot/api/disease/DiseaseDocumentToDiseaseConverterTest.java
support-data-rest/src/test/java/org/uniprot/api/taxonomy/output/TaxonomyEntryFilterTest.java
uniparc-rest/src/test/java/org/uniprot/api/uniparc/controller/UniParcGetIdControllerIT.java
uniparc-rest/src/test/java/org/uniprot/api/uniparc/controller/UniParcSearchControllerIT.java
uniprotkb-rest/src/test/java/org/uniprot/api/uniprotkb/repository/VerifyFieldsInAPIDocumentationExistTest.java

formats code due to maven plugin

REMOVES NEWINSTANCE TO MAKE BUILDERS CONSISTENT

---

common-rest/src/test/java/org/uniprot/api/common/repository/search/facet/FacetResponseConverterTest.java
common-rest/src/test/java/org/uniprot/api/common/repository/search/facet/FakeFacetConfig.java
uniprotkb-rest/src/main/resources/facet.properties
uniprotkb-rest/src/main/resources/uniprotkb_query_param_meta.json

update facet field from popular organism to model organism (TRM-23607)

update facet field from popular organism to model organism (TRM-23607)

---

uniprotkb-rest/src/main/java/org/uniprot/api/uniprotkb/service/PublicationFacetConfig.java
uniprotkb-rest/src/main/java/org/uniprot/api/uniprotkb/service/PublicationService.java
uniprotkb-rest/src/test/java/org/uniprot/api/uniprotkb/controller/UniprotKBByAccessionControllerIT.java
uniprotkb-rest/src/test/java/org/uniprot/api/uniprotkb/controller/UniprotKBEntryControllerIT.java
uniprotkb-rest/src/test/java/org/uniprot/api/uniprotkb/controller/download/resolver/UniProtKBDownloadParamAndResultProvider.java
uniprotkb-rest/src/test/java/org/uniprot/api/uniprotkb/service/PublicationFacetConfigTest.java
uniprotkb-rest/src/test/java/org/uniprot/api/uniprotkb/service/PublicationServiceTest.java

Code Change for TRM-23605 and TRM-23606 that are related

update label for publication page

---

support-data-rest/src/test/java/org/uniprot/api/support/data/configure/controller/UniProtConfigureControllerIT.java
uniprotkb-rest/src/test/java/org/uniprot/api/uniprotkb/controller/UniProtKBSearchControllerIT.java
uniprotkb-rest/src/test/java/org/uniprot/api/uniprotkb/controller/download/IT/BaseUniprotKBDownloadIT.java

Change in test cases due to two new fields.
@eddturner You may review my last commit only.

Trm 23752 add dynamic fields comment feature count

---

common-rest/src/main/java/org/uniprot/api/rest/output/converter/JsonMessageConverter.java
common-rest/src/main/java/org/uniprot/api/rest/output/converter/TsvMessageConverter.java
common-rest/src/main/java/org/uniprot/api/rest/output/converter/XlsMessageConverter.java
common-rest/src/test/java/org/uniprot/api/rest/output/converter/JsonMessageConverterTest.java
common-rest/src/test/java/org/uniprot/api/rest/output/converter/TsvMessageConverterTest.java
common-rest/src/test/java/org/uniprot/api/rest/output/converter/XlsMessageConverterTest.java
unisave-rest/src/main/java/org/uniprot/api/unisave/output/converter/UniSaveJsonMessageConverter.java
unisave-rest/src/test/java/org/uniprot/api/unisave/output/converter/UniSaveJsonMessageConverterTest.java

add remove() in cleanup method to ThreadLocal variables https://rules.sonarsource.com/java/RSPEC-5164

- add remove() to ThreadLocal

---

common-rest/pom.xml
common-rest/src/main/java/org/uniprot/api/common/repository/search/QueryOperator.java
common-rest/src/main/java/org/uniprot/api/common/repository/search/SolrRequest.java
common-rest/src/main/java/org/uniprot/api/common/repository/search/SolrRequestConverter.java
common-rest/src/main/java/org/uniprot/api/rest/request/SearchRequest.java
common-rest/src/main/java/org/uniprot/api/rest/respository/RepositoryConfig.java
common-rest/src/main/java/org/uniprot/api/rest/search/AbstractSolrSortClause.java
common-rest/src/main/java/org/uniprot/api/rest/service/BasicSearchService.java
common-rest/src/test/java/org/uniprot/api/common/repository/search/SolrQueryRepositoryIT.java
common-rest/src/test/java/org/uniprot/api/common/repository/search/SolrRequestConverterTest.java
common-rest/src/test/java/org/uniprot/api/rest/request/SortFieldMetaReaderImplTest.java
common-rest/src/test/java/org/uniprot/api/rest/search/AbstractSolrSortClauseTest.java
proteome-rest/src/main/java/org/uniprot/api/proteome/service/GeneCentricSortClause.java
proteome-rest/src/main/java/org/uniprot/api/proteome/service/ProteomeSortClause.java
support-data-rest/src/main/java/org/uniprot/api/crossref/service/CrossRefSolrSortClause.java
support-data-rest/src/main/java/org/uniprot/api/disease/DiseaseSolrSortClause.java
support-data-rest/src/main/java/org/uniprot/api/keyword/service/KeywordSortClause.java
support-data-rest/src/main/java/org/uniprot/api/literature/service/LiteratureSortClause.java
support-data-rest/src/main/java/org/uniprot/api/subcell/service/SubcellularLocationSortClause.java
support-data-rest/src/main/java/org/uniprot/api/taxonomy/service/TaxonomySortClause.java
uniparc-rest/src/main/java/org/uniprot/api/uniparc/service/UniParcSortClause.java
uniprotkb-rest/src/main/java/org/uniprot/api/uniprotkb/controller/request/UniProtKBRequest.java
uniprotkb-rest/src/main/java/org/uniprot/api/uniprotkb/service/PublicationService.java
uniprotkb-rest/src/main/java/org/uniprot/api/uniprotkb/service/UniProtSolrSortClause.java
uniprotkb-rest/src/test/java/org/uniprot/api/uniprotkb/service/UniProtSolrSortClauseTest.java
uniref-rest/src/main/java/org/uniprot/api/uniref/service/UniRefSortClause.java

... and refactor to directly use apache solr's solrj library.

remove all uses of spring data solr

---

pom.xml
proteome-rest/pom.xml
proteome-rest/src/main/java/org/uniprot/api/proteome/controller/GeneCentricController.java
proteome-rest/src/main/java/org/uniprot/api/proteome/controller/ProteomeController.java
proteome-rest/src/main/java/org/uniprot/api/proteome/request/GeneCentricRequest.java
proteome-rest/src/main/java/org/uniprot/api/proteome/request/ProteomeRequest.java
support-data-rest/pom.xml
uniparc-rest/pom.xml
uniprotkb-rest/pom.xml
uniref-rest/pom.xml

proteome and gene centric swagger document, gene centric can only see two endpoints

proteome and genecentric swagger document

---

support-data-rest/src/main/java/org/uniprot/api/support/data/configure/domain/AdvancedSearchTerm.java
support-data-rest/src/main/java/org/uniprot/api/support/data/configure/service/UniProtKBConfigureService.java
support-data-rest/src/test/java/org/uniprot/api/support/data/configure/domain/AdvancedSearchTermIT.java
support-data-rest/src/test/java/org/uniprot/api/support/data/configure/service/UniProtKBConfigureServiceTest.java

add database cross_ref to advanced search (with database category level) and update go_evidences with the correct evidences

update AdvancedSearchTerm add cross_ref and go_evidences

---

common-rest/src/main/java/org/uniprot/api/rest/service/BasicSearchService.java
proteome-rest/src/main/java/org/uniprot/api/proteome/repository/GeneCentricQueryRepository.java
proteome-rest/src/main/java/org/uniprot/api/proteome/service/GeneCentricEntryConverter.java
proteome-rest/src/main/java/org/uniprot/api/proteome/service/GeneCentricService.java
proteome-rest/src/test/java/org/uniprot/api/proteome/controller/GeneCentricControllerITUtils.java
proteome-rest/src/test/java/org/uniprot/api/proteome/controller/GeneCentricGetIdControllerIT.java
proteome-rest/src/test/java/org/uniprot/api/proteome/controller/GeneCentricSearchControllerIT.java
proteome-rest/src/test/java/org/uniprot/api/proteome/controller/GeneCentricStreamControllerIT.java
proteome-rest/src/test/java/org/uniprot/api/proteome/controller/GeneCentricUpIdSearchControllerIT.java

moved Document conversion to a common module, so it can be used for spark and spring index

code review change 

---

uniprotkb-rest/src/main/resources/uniprotkb_query_param_meta.json
uniprotkb-rest/src/test/java/org/uniprot/api/uniprotkb/controller/UniProtKBSearchControllerIT.java

add uniref_cluster_50, uniref_cluster_90, uniref_cluster_100 and uniparc to uniprotkb-search-fields.json

Add missing search fields

---

uniparc-rest/src/test/java/org/uniprot/api/uniparc/controller/UniParcGetIdControllerIT.java
uniparc-rest/src/test/java/org/uniprot/api/uniparc/controller/UniParcSearchControllerIT.java

add two new fields to keep min and max uniparc xref created and updated resp.

---

common-rest/src/main/java/org/uniprot/api/rest/controller/BasicSearchController.java
common-rest/src/main/java/org/uniprot/api/rest/service/BasicSearchService.java
common-rest/src/test/java/org/uniprot/api/rest/controller/AbstractGetByIdControllerIT.java
idmapping-rest/src/main/java/org/uniprot/api/idmapping/controller/IdMappingJobController.java
idmapping-rest/src/main/java/org/uniprot/api/idmapping/controller/response/JobDetailResponse.java
idmapping-rest/src/test/java/org/uniprot/api/idmapping/controller/IdMappingJobControllerIT.java
support-data-rest/src/main/java/org/uniprot/api/support/data/crossref/controller/CrossRefController.java
support-data-rest/src/main/java/org/uniprot/api/support/data/disease/controller/DiseaseController.java
support-data-rest/src/main/java/org/uniprot/api/support/data/keyword/controller/KeywordController.java
support-data-rest/src/main/java/org/uniprot/api/support/data/literature/controller/LiteratureController.java
support-data-rest/src/main/java/org/uniprot/api/support/data/subcellular/controller/SubcellularLocationController.java
support-data-rest/src/main/java/org/uniprot/api/support/data/taxonomy/controller/TaxonomyController.java
support-data-rest/src/test/java/org/uniprot/api/support/data/crossref/controller/CrossRefGetIdControllerIT.java
support-data-rest/src/test/java/org/uniprot/api/support/data/disease/controller/DiseaseGetIdControllerIT.java
support-data-rest/src/test/java/org/uniprot/api/support/data/keyword/controller/KeywordGetIdControllerIT.java
support-data-rest/src/test/java/org/uniprot/api/support/data/literature/controller/LiteratureGetIdControllerIT.java
support-data-rest/src/test/java/org/uniprot/api/support/data/subcellular/controller/SubcellularLocationGetIdControllerIT.java
support-data-rest/src/test/java/org/uniprot/api/support/data/taxonomy/controller/TaxonomyGetIdControllerIT.java
uniparc-rest/src/main/java/org/uniprot/api/uniparc/service/UniParcQueryService.java

provide support to download single entry with type extension in the request url

---

common-rest/src/main/java/org/uniprot/api/rest/controller/BasicSearchController.java
common-rest/src/main/java/org/uniprot/api/rest/service/query/config/UniProtSolrQueryConfig.java
common-rest/src/main/resources/uniprotkb-query.config
support-data-rest/src/test/java/org/uniprot/api/support/data/taxonomy/controller/TaxonomyGetIdControllerIT.java
uniprotkb-rest/src/main/java/org/uniprot/api/uniprotkb/service/UniProtEntryService.java
uniprotkb-rest/src/test/java/org/uniprot/api/uniprotkb/controller/UniProtKBByAccessionControllerIT.java
uniprotkb-rest/src/test/java/org/uniprot/api/uniprotkb/controller/UniProtKBSearchControllerIT.java

See IT test to understand the use cases. I will be off tomorrow but we can chat on Monday

Fix Inactive ids search for uniprot

---

support-data-rest/src/test/java/org/uniprot/api/support/data/taxonomy/controller/TaxonomyITUtils.java
support-data-rest/src/test/java/org/uniprot/api/support/data/taxonomy/controller/TaxonomySearchControllerIT.java

- fix taxonomy parent
- fix taxonomy ancestors
- remove root taxonomy from solr index

Taxonomy Fixes

---

common-rest/src/main/java/org/uniprot/api/common/repository/search/SolrQueryRepository.java
common-rest/src/main/java/org/uniprot/api/common/repository/search/facet/FacetConverter.java
common-rest/src/main/java/org/uniprot/api/common/repository/search/facet/FacetResponseConverter.java
common-rest/src/main/java/org/uniprot/api/common/repository/search/facet/FacetTupleStreamConverter.java
common-rest/src/main/java/org/uniprot/api/rest/service/StoreStreamerSearchService.java
common-rest/src/main/resources/uniprotkb.facet.properties
common-rest/src/test/java/org/uniprot/api/common/repository/search/facet/FacetResponseConverterTest.java
common-rest/src/test/java/org/uniprot/api/common/repository/search/facet/FacetTupleStreamConverterTest.java
idmapping-rest/src/main/java/org/uniprot/api/idmapping/service/BasicIdService.java
proteome-rest/src/main/resources/proteome.facet.properties
support-data-rest/pom.xml
support-data-rest/src/main/java/org/uniprot/api/support/data/configure/service/UniProtKBConfigureService.java
support-data-rest/src/test/java/org/uniprot/api/support/data/configure/service/UniProtKBConfigureServiceTest.java
uniparc-rest/src/test/java/org/uniprot/api/uniparc/controller/UniParcSearchControllerIT.java
uniprotkb-rest/src/main/java/org/uniprot/api/uniprotkb/service/UniProtEntryService.java
uniprotkb-rest/src/test/java/org/uniprot/api/uniprotkb/controller/UniProtKBByAccessionControllerIT.java
uniprotkb-rest/src/test/java/org/uniprot/api/uniprotkb/controller/UniProtKBGetByAccessionsIT.java
uniprotkb-rest/src/test/java/org/uniprot/api/uniprotkb/controller/UniProtKBGetByAccessionsWithFacetFilterIT.java
uniprotkb-rest/src/test/java/org/uniprot/api/uniprotkb/controller/UniProtKBPublicationControllerIT.java

- fix facet label and order
- also fix search all with brackets

fix facet label and order and also fix search all with brackets

---

support-data-rest/src/main/resources/taxonomy-query.config
support-data-rest/src/test/java/org/uniprot/api/support/data/taxonomy/controller/TaxonomyITUtils.java
support-data-rest/src/test/java/org/uniprot/api/support/data/taxonomy/controller/TaxonomySearchControllerIT.java

TRM-26941: add other names as default search field in taxonomy

---

support-data-rest/src/main/java/org/uniprot/api/support/data/configure/response/UniProtDatabaseDetailResponse.java
support-data-rest/src/test/java/org/uniprot/api/support/data/configure/controller/UniProtKBConfigureControllerIT.java
uniprotkb-rest/src/test/java/org/uniprot/api/uniprotkb/controller/UniProtKBSearchControllerIT.java

https://www.ebi.ac.uk/panda/jira/browse/TRM-27043

remove idMappingName field from allDatabase response

---

support-data-rest/src/main/java/org/uniprot/api/support/data/configure/controller/KeywordConfigureController.java
support-data-rest/src/test/java/org/uniprot/api/support/data/configure/controller/KeywordConfigureControllerIT.java
support-data-rest/src/test/java/org/uniprot/api/support/data/configure/service/KeywordConfigureServiceTest.java

see https://www.ebi.ac.uk/panda/jira/browse/TRM-26571 for details

keyword --> keywords in configure path

---

common-rest/src/test/java/org/uniprot/api/rest/request/ReturnFieldMetaReaderImplTest.java
support-data-rest/src/test/java/org/uniprot/api/support/data/configure/service/CrossRefConfigureServiceTest.java
support-data-rest/src/test/java/org/uniprot/api/support/data/configure/service/DiseaseConfigureServiceTest.java
support-data-rest/src/test/java/org/uniprot/api/support/data/crossref/controller/CrossRefGetIdControllerIT.java
support-data-rest/src/test/java/org/uniprot/api/support/data/disease/controller/DiseaseGetIdControllerIT.java
uniprotkb-rest/src/test/java/org/uniprot/api/uniprotkb/controller/UniProtKBSearchControllerIT.java

see https://www.ebi.ac.uk/panda/jira/browse/TRM-26601 for details.

make return  field stats consistent

---

common-rest/src/main/java/org/uniprot/api/rest/output/UniProtMediaType.java
common-rest/src/main/java/org/uniprot/api/rest/output/converter/AbstractUUWHttpMessageConverter.java
common-rest/src/test/java/org/uniprot/api/rest/output/UniProtMediaTypeTest.java
proteome-rest/src/main/java/org/uniprot/api/proteome/service/ProteomeQueryService.java
proteome-rest/src/test/java/org/uniprot/api/proteome/controller/ProteomeSearchControllerIT.java
proteome-rest/src/test/java/org/uniprot/api/proteome/controller/ProteomeStreamControllerIT.java
support-data-rest/src/main/java/org/uniprot/api/support/data/common/MessageConverterConfig.java
support-data-rest/src/main/java/org/uniprot/api/support/data/configure/service/IdMappingConfigureService.java
support-data-rest/src/test/java/org/uniprot/api/support/data/configure/controller/IdMappingConfigureControllerIT.java
support-data-rest/src/test/java/org/uniprot/api/support/data/keyword/controller/KeywordSearchControllerIT.java

https://www.ebi.ac.uk/panda/jira/browse/TRM-27305

Make proteomes REST API search for excluded proteomes as with uniprot.org

---

uniprotkb-rest/src/main/java/org/uniprot/api/uniprotkb/controller/UniProtKBController.java
uniprotkb-rest/src/main/java/org/uniprot/api/uniprotkb/service/UniProtEntryService.java
uniprotkb-rest/src/test/java/org/uniprot/api/uniprotkb/controller/UniProtKBByAccessionControllerIT.java

Allow ID (TRM-27995) and accession with version (TRM-27996) for uniprotkb accession endpoint

Allow ID (TRM-27995) and accession with version (TRM-27996)

---

uniprotkb-rest/src/main/java/org/uniprot/api/uniprotkb/service/UniProtEntryService.java
uniprotkb-rest/src/test/java/org/uniprot/api/uniprotkb/controller/UniProtKBByAccessionControllerIT.java
uniprotkb-rest/src/test/java/org/uniprot/api/uniprotkb/controller/UniProtKBSearchControllerIT.java

TRM-28235: enable search and get by id for canonical isoform that does not have isoforms

TRM-28235: enable search and get by id for canonical isoform

---

support-data-rest/src/main/java/org/uniprot/api/support/data/literature/controller/LiteratureController.java
support-data-rest/src/main/resources/message.properties
support-data-rest/src/test/java/org/uniprot/api/support/data/literature/controller/LiteratureGetIdControllerIT.java
support-data-rest/src/test/java/org/uniprot/api/support/data/literature/controller/LiteratureSearchControllerIT.java

TRM-28329: improve citation id Regex

TRM-28329: improve citation id Regex

---

common-rest/src/main/resources/valid-field-whitelist.properties
common-rest/src/test/java/org/uniprot/api/rest/validation/QueryFieldValidatorTest.java

TRM-28439: add BioCyc and veupathdb Ids as whitelist field

TRM-28439: add BioCyc and veupathdb Ids as whitelist field

---

support-data-rest/src/test/java/org/uniprot/api/support/data/configure/response/AdvancedSearchTermIT.java
support-data-rest/src/test/java/org/uniprot/api/support/data/configure/service/UniProtKBConfigureServiceTest.java
uniprotkb-rest/src/main/resources/uniprotkb_query_param_meta.json
uniprotkb-rest/src/test/java/org/uniprot/api/uniprotkb/controller/UniProtKBSearchControllerIT.java

Just updating test that failed due to the changes done in store

Add Any experimental evidence search field in advanced search menu

---

common-rest/src/main/java/org/uniprot/api/rest/controller/BasicDownloadController.java
common-rest/src/main/java/org/uniprot/api/rest/download/model/JobStatus.java
uniprotkb-rest/src/test/java/org/uniprot/api/uniprotkb/controller/AbstractDownloadControllerIT.java
uniprotkb-rest/src/test/java/org/uniprot/api/uniprotkb/controller/UniProtKBDownloadControllerIT.java
uniprotkb-rest/src/test/java/org/uniprot/api/uniprotkb/queue/EmbeddingsTestConsumer.java

Please see https://www.ebi.ac.uk/panda/jira/browse/TRM-29502 for details

map aa embeddings status processing and unfinished to running for user

---

uniprotkb-rest/src/main/java/org/uniprot/api/uniprotkb/service/UniProtEntryService.java
uniprotkb-rest/src/test/java/org/uniprot/api/uniprotkb/controller/UniProtKBByAccessionControllerIT.java
uniprotkb-rest/src/test/java/org/uniprot/api/uniprotkb/service/UniProtEntryServiceTest.java

More details in Jira description

TRM-29946: Improve get entry by protein id with 2 tracked ids (obsolete ids) only

---

support-data-rest/src/main/java/org/uniprot/api/support/data/configure/service/UniProtKBConfigureService.java
support-data-rest/src/test/java/org/uniprot/api/support/data/configure/controller/UniProtKBConfigureControllerIT.java

See https://www.ebi.ac.uk/panda/jira/browse/TRM-30196 for details

internal cross ref in uniprotkb/allDatabase endpoint

---

common-rest/src/main/java/org/uniprot/api/common/repository/search/page/impl/CursorPage.java
common-rest/src/test/java/org/uniprot/api/common/repository/search/page/impl/CursorPageTest.java

You can look in the TRM-30353 description for more details

TRM-30353: Improve pagination next URL encoding issue when searching with + char

---

common-rest/src/main/java/org/uniprot/api/rest/controller/BasicSearchController.java
common-rest/src/main/java/org/uniprot/api/rest/request/HttpServletRequestContentTypeMutator.java
common-rest/src/test/java/org/uniprot/api/rest/controller/BasicSearchControllerTest.java

See https://www.ebi.ac.uk/panda/jira/browse/TRM-30599 for details.

bypass gatekeeper for stream requests coming from browser

---

common-rest/src/main/java/org/uniprot/api/rest/service/query/UniProtQueryProcessor.java
common-rest/src/main/java/org/uniprot/api/rest/validation/ValidSolrQueryFields.java
common-rest/src/main/java/org/uniprot/api/rest/validation/ValidSolrQuerySyntax.java
common-rest/src/test/java/org/uniprot/api/rest/service/query/UniProtQueryProcessorTest.java

Details here https://www.ebi.ac.uk/panda/jira/browse/TRM-30928

escape < and > in solr

---

support-data-rest/src/test/java/org/uniprot/api/support/data/configure/controller/IdMappingConfigureControllerIT.java
support-data-rest/src/test/java/org/uniprot/api/support/data/configure/service/UniProtKBConfigureServiceTest.java

changed xrefs

---

uniprotkb-common/src/test/java/org/uniprot/api/uniprotkb/common/service/uniprotkb/UniProtEntryQueryResultsConverterTest.java
uniprotkb-common/src/test/java/org/uniprot/api/uniprotkb/common/utils/UniProtKBAsyncDownloadUtils.java
uniprotkb-rest/src/test/java/org/uniprot/api/uniprotkb/controller/UniProtKBByAccessionControllerIT.java
uniprotkb-rest/src/test/java/org/uniprot/api/uniprotkb/controller/UniProtKBSearchControllerIT.java
unisave-rest/src/main/java/org/uniprot/api/unisave/repository/UniSaveRepository.java
unisave-rest/src/main/java/org/uniprot/api/unisave/service/impl/UniSaveServiceImpl.java
unisave-rest/src/test/java/org/uniprot/api/unisave/controller/UniSaveControllerTest.java
unisave-rest/src/test/java/org/uniprot/api/unisave/repository/UniSaveRepositoryIT.java
unisave-rest/src/test/java/org/uniprot/api/unisave/service/impl/UniSaveServiceImplTest.java

The main change is that we will not return deletedReason when it is Unknown, also description changes

TRM-27505: Changes after consortium review

---

uniprotkb-rest/src/test/java/org/uniprot/api/uniprotkb/controller/UniProtKBSearchControllerIT.java

provide search support by chebi name and synonyms

---

idmapping-common/src/main/java/org/uniprot/api/idmapping/common/request/ValidFromAndTo.java
idmapping-common/src/test/java/org/uniprot/api/idmapping/common/request/ValidFromAndToTest.java
idmapping-rest/src/test/java/org/uniprot/api/idmapping/controller/IdMappingJobControllerIT.java
support-data-rest/src/test/java/org/uniprot/api/support/data/statistics/controller/StatisticsControllerIT.java

See Jira TRM-32847 for details.

remove taxId validation from idmapping
